<a href="https://colab.research.google.com/github/Mark12481632/Intro_ML/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Imports:
# ========

import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
# Example tensors
data_lst_1 = [[1,2,3,4,5], [6,7,8,9,10]]
tensor_1 = torch.tensor(data_lst_1)
print(tensor_1)
print(tensor_1.shape, tensor_1.size(), tensor_1.dtype)

data_lst_2 = [[1,2,1,2,1], [4,4,1,2,3]]
tensor_2 = torch.tensor(data_lst_2)
print(tensor_2)
print(tensor_2.shape, tensor_2.size(), tensor_2.dtype)

# Element by element operations possible with same shape tensors:
print(tensor_1 + tensor_2)
print(tensor_1 - tensor_2)
print(tensor_1 * tensor_2)
print(tensor_1 / tensor_2)

# Tensor multiplication.
print(tensor_1 + tensor_2)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
torch.Size([2, 5]) torch.Size([2, 5]) torch.int64
tensor([[1, 2, 1, 2, 1],
        [4, 4, 1, 2, 3]])
torch.Size([2, 5]) torch.Size([2, 5]) torch.int64
tensor([[ 2,  4,  4,  6,  6],
        [10, 11,  9, 11, 13]])
tensor([[0, 0, 2, 2, 4],
        [2, 3, 7, 7, 7]])
tensor([[ 1,  4,  3,  8,  5],
        [24, 28,  8, 18, 30]])
tensor([[1.0000, 1.0000, 3.0000, 2.0000, 5.0000],
        [1.5000, 1.7500, 8.0000, 4.5000, 3.3333]])
tensor([[ 2,  4,  4,  6,  6],
        [10, 11,  9, 11, 13]])


In [17]:
# Create simple NN

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

linear_layer = nn.Linear(in_features=3, out_features=2)
output = linear_layer(input_tensor)
print(output)

print(linear_layer.weight)
print(linear_layer.bias)

tensor([[-0.4696,  0.5197]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.0575, -0.5755,  0.1649],
        [-0.2138,  0.1136, -0.0937]], requires_grad=True)
Parameter containing:
tensor([-0.1492,  0.5201], requires_grad=True)


In [23]:
# Adding layers to network:
n_features = 8
n_classes = 2

# nn.Linear(8, 4) means this layer has 4 neurons.
#                 Each neuron has 9 (8+1 bias) inputs.
#                 Hence, total of 4 * 9 = 36 params required.

# Number of inputs at layer (n+1) must = number outputs of layer n.
model = nn.Sequential(nn.Linear(n_features, 4),
                      nn.Linear(4, n_classes))

# Above model has (8+1) * 4 + (4+1)*2 = 36 + 10 = 46 params to train in total.

print(model)

# Show number of params needed to be trainied using numel():
total = 0
for param in model.parameters():
    total += param.numel()
print(total)

Sequential(
  (0): Linear(in_features=8, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=2, bias=True)
)
46


In [29]:
# Read in data file.
# Note: type (0 => bird), (1 => mammal), (2 => reptile)
data = pd.read_csv("https://raw.githubusercontent.com/Mark12481632/Intro_ML/refs/heads/main/animals.csv")
data = data.iloc[:, 1:]
features = data.to_numpy()
print(features)

[[0 1 1 0 0 2 1 0]
 [0 1 1 0 1 2 1 0]
 [1 0 0 1 1 4 1 1]
 [1 0 0 1 0 4 1 1]
 [0 0 1 0 1 4 1 2]]
